# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo:4.0
    restart: always
    command: --noprealloc --smallfiles --replSet=rs0
    ports:
      - 27017:27017
  
  elastic:
    image: elasticsearch:7.5.1
    environment:
      discovery.type: "single-node"
    ports:
      - 9200:9200
