/** The progress step that an importer is at. */
export const ProgressStep = Object.freeze({
	UPLOADING: 'importer_uploading',
	NEW: 'importer_new',
	DOWNLOADING_FILE_URL: 'downloading_file_url',
	DOWNLOAD_COMPLETE: 'download_complete',
	PREPARING_STARTED: 'importer_preparing_started',
	PREPARING_USERS: 'importer_preparing_users',
	PREPARING_CHANNELS: 'importer_preparing_channels',
	PREPARING_MESSAGES: 'importer_preparing_messages',
	PREPARING_AVATARS: 'importer_preparing_avatars',
	PREPARING_NAMES: 'importer_preparing_names',
	PREPARING_STATUSES: 'importer_preparing_statuses',
	USER_SELECTION: 'importer_user_selection',
	IMPORTING_STARTED: 'importer_importing_started',
	IMPORTING_USERS: 'importer_importing_users',
	IMPORTING_CHANNELS: 'importer_importing_channels',
	IMPORTING_MESSAGES: 'importer_importing_messages',
	IMPORTING_AVATARS: 'importer_importing_avatars',
	IMPORTING_NAMES: 'importer_importing_names',
	IMPORTING_STATUSES: 'importer_importing_statuses',
	FINISHING: 'importer_finishing',
	DONE: 'importer_done',
	ERROR: 'importer_import_failed',
	CANCELLED: 'importer_import_cancelled',
});
